version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dcfs-app
    env_file:
      - ./env/.env.app
    depends_on:
      - db
      - redis
    ports:
      - "4000:4000"
    networks:
      - dcfs-net

  db:
    image: postgres:16-alpine
    container_name: dcfs-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: dcfs_user
      POSTGRES_PASSWORD: dcfs_password
      POSTGRES_DB: dcfs_dev
    volumes:
      - dcfs-db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - dcfs-net

  redis:
    image: redis:7-alpine
    container_name: dcfs-redis
    restart: unless-stopped
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - "6379:6379"
    networks:
      - dcfs-net

  nginx:
    image: nginx:1.27-alpine
    container_name: dcfs-nginx
    restart: unless-stopped
    depends_on:
      - app
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - dcfs-net

volumes:
  dcfs-db-data:

networks:
  dcfs-net:
    driver: bridge

